services:
    webapp:
        image: ysof_student
        build:
            context: ./
            dockerfile: Dockerfile
        restart: unless-stopped
        networks:
            - ysof_student
        container_name: ysof_student_${NODE_ENV}
        ports:
            - "3000:80"