/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated/route'
import { Route as auth500Import } from './routes/(auth)/500'

// Create Virtual Routes

const AuthenticatedIndexLazyImport = createFileRoute('/_authenticated/')()
const AuthenticatedXinNghiPhepLazyImport = createFileRoute(
  '/_authenticated/xin-nghi-phep',
)()
const AuthenticatedTaiKhoanLazyImport = createFileRoute(
  '/_authenticated/tai-khoan',
)()
const AuthenticatedLuongGiaLazyImport = createFileRoute(
  '/_authenticated/luong-gia',
)()
const AuthenticatedDiemDanhLazyImport = createFileRoute(
  '/_authenticated/diem-danh',
)()
const AuthenticatedDanhSachHocVienLazyImport = createFileRoute(
  '/_authenticated/danh-sach-hoc-vien',
)()
const AuthenticatedDanhSachChuDeLazyImport = createFileRoute(
  '/_authenticated/danh-sach-chu-de',
)()
const AuthenticatedDangKyHocLazyImport = createFileRoute(
  '/_authenticated/dang-ky-hoc',
)()
const errors503LazyImport = createFileRoute('/(errors)/503')()
const errors500LazyImport = createFileRoute('/(errors)/500')()
const errors404LazyImport = createFileRoute('/(errors)/404')()
const errors403LazyImport = createFileRoute('/(errors)/403')()
const errors401LazyImport = createFileRoute('/(errors)/401')()
const authForgotPasswordLazyImport = createFileRoute(
  '/(auth)/forgot-password',
)()
const authDangNhapLazyImport = createFileRoute('/(auth)/dang-nhap')()

// Create/Update Routes

const AuthenticatedRouteRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexLazyRoute = AuthenticatedIndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/index.lazy').then((d) => d.Route),
)

const AuthenticatedXinNghiPhepLazyRoute =
  AuthenticatedXinNghiPhepLazyImport.update({
    id: '/xin-nghi-phep',
    path: '/xin-nghi-phep',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/xin-nghi-phep.lazy').then((d) => d.Route),
  )

const AuthenticatedTaiKhoanLazyRoute = AuthenticatedTaiKhoanLazyImport.update({
  id: '/tai-khoan',
  path: '/tai-khoan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/tai-khoan.lazy').then((d) => d.Route),
)

const AuthenticatedLuongGiaLazyRoute = AuthenticatedLuongGiaLazyImport.update({
  id: '/luong-gia',
  path: '/luong-gia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/luong-gia.lazy').then((d) => d.Route),
)

const AuthenticatedDiemDanhLazyRoute = AuthenticatedDiemDanhLazyImport.update({
  id: '/diem-danh',
  path: '/diem-danh',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/diem-danh.lazy').then((d) => d.Route),
)

const AuthenticatedDanhSachHocVienLazyRoute =
  AuthenticatedDanhSachHocVienLazyImport.update({
    id: '/danh-sach-hoc-vien',
    path: '/danh-sach-hoc-vien',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/danh-sach-hoc-vien.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedDanhSachChuDeLazyRoute =
  AuthenticatedDanhSachChuDeLazyImport.update({
    id: '/danh-sach-chu-de',
    path: '/danh-sach-chu-de',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/danh-sach-chu-de.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedDangKyHocLazyRoute = AuthenticatedDangKyHocLazyImport.update(
  {
    id: '/dang-ky-hoc',
    path: '/dang-ky-hoc',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any,
).lazy(() =>
  import('./routes/_authenticated/dang-ky-hoc.lazy').then((d) => d.Route),
)

const errors503LazyRoute = errors503LazyImport
  .update({
    id: '/(errors)/503',
    path: '/503',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/503.lazy').then((d) => d.Route))

const errors500LazyRoute = errors500LazyImport
  .update({
    id: '/(errors)/500',
    path: '/500',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/500.lazy').then((d) => d.Route))

const errors404LazyRoute = errors404LazyImport
  .update({
    id: '/(errors)/404',
    path: '/404',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/404.lazy').then((d) => d.Route))

const errors403LazyRoute = errors403LazyImport
  .update({
    id: '/(errors)/403',
    path: '/403',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/403.lazy').then((d) => d.Route))

const errors401LazyRoute = errors401LazyImport
  .update({
    id: '/(errors)/401',
    path: '/401',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/401.lazy').then((d) => d.Route))

const authForgotPasswordLazyRoute = authForgotPasswordLazyImport
  .update({
    id: '/(auth)/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() =>
    import('./routes/(auth)/forgot-password.lazy').then((d) => d.Route),
  )

const authDangNhapLazyRoute = authDangNhapLazyImport
  .update({
    id: '/(auth)/dang-nhap',
    path: '/dang-nhap',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(auth)/dang-nhap.lazy').then((d) => d.Route))

const auth500Route = auth500Import.update({
  id: '/(auth)/500',
  path: '/500',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/500': {
      id: '/(auth)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof auth500Import
      parentRoute: typeof rootRoute
    }
    '/(auth)/dang-nhap': {
      id: '/(auth)/dang-nhap'
      path: '/dang-nhap'
      fullPath: '/dang-nhap'
      preLoaderRoute: typeof authDangNhapLazyImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordLazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503LazyImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/dang-ky-hoc': {
      id: '/_authenticated/dang-ky-hoc'
      path: '/dang-ky-hoc'
      fullPath: '/dang-ky-hoc'
      preLoaderRoute: typeof AuthenticatedDangKyHocLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/danh-sach-chu-de': {
      id: '/_authenticated/danh-sach-chu-de'
      path: '/danh-sach-chu-de'
      fullPath: '/danh-sach-chu-de'
      preLoaderRoute: typeof AuthenticatedDanhSachChuDeLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/danh-sach-hoc-vien': {
      id: '/_authenticated/danh-sach-hoc-vien'
      path: '/danh-sach-hoc-vien'
      fullPath: '/danh-sach-hoc-vien'
      preLoaderRoute: typeof AuthenticatedDanhSachHocVienLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/diem-danh': {
      id: '/_authenticated/diem-danh'
      path: '/diem-danh'
      fullPath: '/diem-danh'
      preLoaderRoute: typeof AuthenticatedDiemDanhLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/luong-gia': {
      id: '/_authenticated/luong-gia'
      path: '/luong-gia'
      fullPath: '/luong-gia'
      preLoaderRoute: typeof AuthenticatedLuongGiaLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/tai-khoan': {
      id: '/_authenticated/tai-khoan'
      path: '/tai-khoan'
      fullPath: '/tai-khoan'
      preLoaderRoute: typeof AuthenticatedTaiKhoanLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/xin-nghi-phep': {
      id: '/_authenticated/xin-nghi-phep'
      path: '/xin-nghi-phep'
      fullPath: '/xin-nghi-phep'
      preLoaderRoute: typeof AuthenticatedXinNghiPhepLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDangKyHocLazyRoute: typeof AuthenticatedDangKyHocLazyRoute
  AuthenticatedDanhSachChuDeLazyRoute: typeof AuthenticatedDanhSachChuDeLazyRoute
  AuthenticatedDanhSachHocVienLazyRoute: typeof AuthenticatedDanhSachHocVienLazyRoute
  AuthenticatedDiemDanhLazyRoute: typeof AuthenticatedDiemDanhLazyRoute
  AuthenticatedLuongGiaLazyRoute: typeof AuthenticatedLuongGiaLazyRoute
  AuthenticatedTaiKhoanLazyRoute: typeof AuthenticatedTaiKhoanLazyRoute
  AuthenticatedXinNghiPhepLazyRoute: typeof AuthenticatedXinNghiPhepLazyRoute
  AuthenticatedIndexLazyRoute: typeof AuthenticatedIndexLazyRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDangKyHocLazyRoute: AuthenticatedDangKyHocLazyRoute,
  AuthenticatedDanhSachChuDeLazyRoute: AuthenticatedDanhSachChuDeLazyRoute,
  AuthenticatedDanhSachHocVienLazyRoute: AuthenticatedDanhSachHocVienLazyRoute,
  AuthenticatedDiemDanhLazyRoute: AuthenticatedDiemDanhLazyRoute,
  AuthenticatedLuongGiaLazyRoute: AuthenticatedLuongGiaLazyRoute,
  AuthenticatedTaiKhoanLazyRoute: AuthenticatedTaiKhoanLazyRoute,
  AuthenticatedXinNghiPhepLazyRoute: AuthenticatedXinNghiPhepLazyRoute,
  AuthenticatedIndexLazyRoute: AuthenticatedIndexLazyRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedRouteRouteWithChildren
  '/500': typeof errors500LazyRoute
  '/dang-nhap': typeof authDangNhapLazyRoute
  '/forgot-password': typeof authForgotPasswordLazyRoute
  '/401': typeof errors401LazyRoute
  '/403': typeof errors403LazyRoute
  '/404': typeof errors404LazyRoute
  '/503': typeof errors503LazyRoute
  '/dang-ky-hoc': typeof AuthenticatedDangKyHocLazyRoute
  '/danh-sach-chu-de': typeof AuthenticatedDanhSachChuDeLazyRoute
  '/danh-sach-hoc-vien': typeof AuthenticatedDanhSachHocVienLazyRoute
  '/diem-danh': typeof AuthenticatedDiemDanhLazyRoute
  '/luong-gia': typeof AuthenticatedLuongGiaLazyRoute
  '/tai-khoan': typeof AuthenticatedTaiKhoanLazyRoute
  '/xin-nghi-phep': typeof AuthenticatedXinNghiPhepLazyRoute
  '/': typeof AuthenticatedIndexLazyRoute
}

export interface FileRoutesByTo {
  '/500': typeof errors500LazyRoute
  '/dang-nhap': typeof authDangNhapLazyRoute
  '/forgot-password': typeof authForgotPasswordLazyRoute
  '/401': typeof errors401LazyRoute
  '/403': typeof errors403LazyRoute
  '/404': typeof errors404LazyRoute
  '/503': typeof errors503LazyRoute
  '/dang-ky-hoc': typeof AuthenticatedDangKyHocLazyRoute
  '/danh-sach-chu-de': typeof AuthenticatedDanhSachChuDeLazyRoute
  '/danh-sach-hoc-vien': typeof AuthenticatedDanhSachHocVienLazyRoute
  '/diem-danh': typeof AuthenticatedDiemDanhLazyRoute
  '/luong-gia': typeof AuthenticatedLuongGiaLazyRoute
  '/tai-khoan': typeof AuthenticatedTaiKhoanLazyRoute
  '/xin-nghi-phep': typeof AuthenticatedXinNghiPhepLazyRoute
  '/': typeof AuthenticatedIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/500': typeof auth500Route
  '/(auth)/dang-nhap': typeof authDangNhapLazyRoute
  '/(auth)/forgot-password': typeof authForgotPasswordLazyRoute
  '/(errors)/401': typeof errors401LazyRoute
  '/(errors)/403': typeof errors403LazyRoute
  '/(errors)/404': typeof errors404LazyRoute
  '/(errors)/500': typeof errors500LazyRoute
  '/(errors)/503': typeof errors503LazyRoute
  '/_authenticated/dang-ky-hoc': typeof AuthenticatedDangKyHocLazyRoute
  '/_authenticated/danh-sach-chu-de': typeof AuthenticatedDanhSachChuDeLazyRoute
  '/_authenticated/danh-sach-hoc-vien': typeof AuthenticatedDanhSachHocVienLazyRoute
  '/_authenticated/diem-danh': typeof AuthenticatedDiemDanhLazyRoute
  '/_authenticated/luong-gia': typeof AuthenticatedLuongGiaLazyRoute
  '/_authenticated/tai-khoan': typeof AuthenticatedTaiKhoanLazyRoute
  '/_authenticated/xin-nghi-phep': typeof AuthenticatedXinNghiPhepLazyRoute
  '/_authenticated/': typeof AuthenticatedIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/500'
    | '/dang-nhap'
    | '/forgot-password'
    | '/401'
    | '/403'
    | '/404'
    | '/503'
    | '/dang-ky-hoc'
    | '/danh-sach-chu-de'
    | '/danh-sach-hoc-vien'
    | '/diem-danh'
    | '/luong-gia'
    | '/tai-khoan'
    | '/xin-nghi-phep'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/500'
    | '/dang-nhap'
    | '/forgot-password'
    | '/401'
    | '/403'
    | '/404'
    | '/503'
    | '/dang-ky-hoc'
    | '/danh-sach-chu-de'
    | '/danh-sach-hoc-vien'
    | '/diem-danh'
    | '/luong-gia'
    | '/tai-khoan'
    | '/xin-nghi-phep'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/500'
    | '/(auth)/dang-nhap'
    | '/(auth)/forgot-password'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/dang-ky-hoc'
    | '/_authenticated/danh-sach-chu-de'
    | '/_authenticated/danh-sach-hoc-vien'
    | '/_authenticated/diem-danh'
    | '/_authenticated/luong-gia'
    | '/_authenticated/tai-khoan'
    | '/_authenticated/xin-nghi-phep'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  auth500Route: typeof auth500Route
  authDangNhapLazyRoute: typeof authDangNhapLazyRoute
  authForgotPasswordLazyRoute: typeof authForgotPasswordLazyRoute
  errors401LazyRoute: typeof errors401LazyRoute
  errors403LazyRoute: typeof errors403LazyRoute
  errors404LazyRoute: typeof errors404LazyRoute
  errors500LazyRoute: typeof errors500LazyRoute
  errors503LazyRoute: typeof errors503LazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  auth500Route: auth500Route,
  authDangNhapLazyRoute: authDangNhapLazyRoute,
  authForgotPasswordLazyRoute: authForgotPasswordLazyRoute,
  errors401LazyRoute: errors401LazyRoute,
  errors403LazyRoute: errors403LazyRoute,
  errors404LazyRoute: errors404LazyRoute,
  errors500LazyRoute: errors500LazyRoute,
  errors503LazyRoute: errors503LazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/(auth)/500",
        "/(auth)/dang-nhap",
        "/(auth)/forgot-password",
        "/(errors)/401",
        "/(errors)/403",
        "/(errors)/404",
        "/(errors)/500",
        "/(errors)/503"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated/route.tsx",
      "children": [
        "/_authenticated/dang-ky-hoc",
        "/_authenticated/danh-sach-chu-de",
        "/_authenticated/danh-sach-hoc-vien",
        "/_authenticated/diem-danh",
        "/_authenticated/luong-gia",
        "/_authenticated/tai-khoan",
        "/_authenticated/xin-nghi-phep",
        "/_authenticated/"
      ]
    },
    "/(auth)/500": {
      "filePath": "(auth)/500.tsx"
    },
    "/(auth)/dang-nhap": {
      "filePath": "(auth)/dang-nhap.lazy.tsx"
    },
    "/(auth)/forgot-password": {
      "filePath": "(auth)/forgot-password.lazy.tsx"
    },
    "/(errors)/401": {
      "filePath": "(errors)/401.lazy.tsx"
    },
    "/(errors)/403": {
      "filePath": "(errors)/403.lazy.tsx"
    },
    "/(errors)/404": {
      "filePath": "(errors)/404.lazy.tsx"
    },
    "/(errors)/500": {
      "filePath": "(errors)/500.lazy.tsx"
    },
    "/(errors)/503": {
      "filePath": "(errors)/503.lazy.tsx"
    },
    "/_authenticated/dang-ky-hoc": {
      "filePath": "_authenticated/dang-ky-hoc.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/danh-sach-chu-de": {
      "filePath": "_authenticated/danh-sach-chu-de.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/danh-sach-hoc-vien": {
      "filePath": "_authenticated/danh-sach-hoc-vien.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/diem-danh": {
      "filePath": "_authenticated/diem-danh.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/luong-gia": {
      "filePath": "_authenticated/luong-gia.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/tai-khoan": {
      "filePath": "_authenticated/tai-khoan.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/xin-nghi-phep": {
      "filePath": "_authenticated/xin-nghi-phep.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.lazy.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
